import os
from groq import Groq

class FeedbackService:
    def __init__(self):
        self.api_key = os.getenv("GROQ_API_KEY", "")
        # If API key is dummy or empty, we will skip calling Groq and return a default template
        self.is_dummy = self.api_key == "" or self.api_key == "gsk_dummy_key_here"
        
        if not self.is_dummy:
            try:
                self.client = Groq(api_key=self.api_key)
            except Exception as e:
                print(f"Error initializing Groq client: {e}")
                self.is_dummy = True

    def generate_feedback(self, transcript: str, overall_score: float, words: list[dict]) -> str:
        """
        Calls Groq API to generate pronunciation feedback based on phoneme mismatch data.
        Falls back to a detailed placeholder if using a dummy API key.
        """
        if self.is_dummy:
            return None

        try:
            # Filter words with less than 80% score to show the mistakes
            mispronounced = [
                f"Word: '{w['word']}' (Expected phonemes: {w['expected']}, Actual phonemes: {w['actual']}, Score: {w['score']})"
                for w in words if w['score'] < 80
            ]
            mispronounced_str = "\n".join(mispronounced) if mispronounced else "None (great pronunciation!)"

            prompt = f"""
You are an expert English pronunciation coach, speech therapist, and linguist.

Your task is to analyze a pronunciation assessment generated by a speech processing system.

IMPORTANT RULES:
- Base your analysis ONLY on the information provided.
- Do NOT invent pronunciation mistakes.
- Do NOT assume a pronunciation error if the phoneme comparison is inconclusive.
- If a word is a proper noun (person name, company, place, etc.), mention that pronunciation may vary naturally.
- Keep your feedback encouraging, educational, and friendly.
- CRITICAL: Do NOT list or analyze the problematic words one-by-one. You must synthesize the errors and focus ONLY on the general phonetic patterns and trends (e.g., issues with specific vowel sounds, final consonant deletion, or transition struggles). Group similar errors together.

## Assessment

Transcript:
"{transcript}"

Overall pronunciation score:
{overall_score:.2f}/100

Words with pronunciation issues:
{mispronounced_str}

--------------------------------------------

Please generate your feedback strictly following this structure:

# Error Analysis Summary
Provide a cohesive, summarized analysis combining all detected errors into general trends. Highlight the main phonetic trends, consonant/vowel issues, or sound omissions. Do NOT list the words one-by-one. Explain the physical mechanics (tongue position, mouth shape, airflow) to correct these patterns.

# Practice Plan
Create a short daily practice routine (5 minutes) based on these patterns.

# Top 5 Sounds To Practice
Rank the specific sounds (vowels, consonants, or blends) that need the most attention. You MUST use this exact format for each of the 5 sounds:
1. **Sound [Phonetic Symbol]** - Description of the error trend and how to practice.
2. **Sound [Phonetic Symbol]** - Description...
(List exactly 5 items, one per line. Do not write any other intro or outro text in this section).

# Final Encouragement
End with a positive, motivating paragraph for the learner.

Use clean Markdown formatting with headings, tables where useful, bullet points, and bold text.
Do not mention JSON or internal analysis.
"""

            chat_completion = self.client.chat.completions.create(
                messages=[
                    {"role": "system", "content": "You are a helpful, encouraging English speech coach."},
                    {"role": "user", "content": prompt}
                ],
                model="llama-3.1-8b-instant",
                temperature=0.7,
                max_tokens=1024,
            )

            return chat_completion.choices[0].message.content
        except Exception as e:
            print(f"Error generating Groq feedback: {e}")
            return None
